---
- name: Ensure zsh is installed
  package: name=zsh state=present
  become: yes
- name: Install zshrc
  copy: src=zshrc dest=~/.zshrc
- name: Setup as default shell
  user: name=samuel shell=/usr/bin/zsh
  become: yes
