---
- name: Install i3
  package: name=i3 state=present
  become: yes
- name: Create config dir
  file: path=~/.i3 state=directory
- name: Copy config file
  template: src=config.j2 dest=~/.i3/config
- name: Copy i3status config file
  copy: src=i3status.conf dest=~/.i3status.conf
