---
- name: Add yarn apt key
  apt_key: url=https://dl.yarnpkg.com/debian/pubkey.gpg
  become: yes
- name: Add yarn repo
  apt_repository:
    repo: deb https://dl.yarnpkg.com/debian/ stable main
    filename: yarn
    state: present
  become: yes
- name: Install yarn
  apt: name=yarn state=present
  become: yes
