---
- name: Setup apt key
  apt_key: keyserver=hkp://ha.pool.sks-keyservers.net:80 id=58118E89F3A912897C070ADBF76221572C52609D
  become: yes
- name: Add docker repository
  apt_repository:
    repo: deb https://apt.dockerproject.org/repo ubuntu-xenial main
    filename: docker
    state: present
  become: yes
- name: Install docker
  apt: name={{item}}
  with_items:
    - linux-image-extra-{{ansible_kernel}}
    - linux-image-extra-virtual
    - docker-engine
  become: yes
- name: Start docker
  service: name=docker state=started enabled=yes
  become: yes
# - name: Add docker group
- name: install docker-compose
  pip: name=docker-compose state=present
  become: yes
