---
- set_fact:
    fira_dir: /usr/share/fonts/opentype/fira
- name: Create fira font dir
  file: dest={{fira_dir}} state=directory
  become: yes
- name: Download Fira Mono Nerd fonts
  unarchive: src=https://github.com/ryanoasis/nerd-fonts/releases/download/v1.1.0/FiraMono.zip dest={{fira_dir}} remote_src=yes
  become: yes
